name: Test CI

on: push

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      pull-requests: write
      contents: write
      checks: write
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'
    - uses: jwalton/gh-find-current-pr@v1
      id: findpr
    - run: yarn install --inline-builds
    - run: yarn build
    - run: yarn test-ci
    - uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        coverage-file: ./report.json
        prnumber: ${{ steps.findPr.outputs.number }}
        annotations: none
    